name: Deploy to Website to Github Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
        npm install react-scripts --save-dev
        npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy
